language: c

compiler:
  - gcc

matrix:
  include:
    - compiler: gcc
      env: CONFIGURE_OPTION='-Duse64bitall'
    - compiler: gcc
      env: CONFIGURE_OPTION='-Duse64bitall -Dusethreads'
    - compiler: clang

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential libtool
  - sudo apt-get build-dep perl perl-base

before_script:
  - ./Configure -des -Dusedevel -Uversiononly -Dcc=$CC $CONFIGURE_OPTION -Dprefix=$HOME/perl-blead -DDEBUGGING
script:
  - make test && make install && $HOME/perl-blead/bin/perlivp
after_script:
cache:
  apt: true

