language: c

compiler:
  - gcc

env: CONFIGURE_OPTION='-Dcc=gcc'

matrix:
  include:
    - compiler: gcc
      env: CONFIGURE_OPTION='-Duse64bitall -Dcc=gcc' COVERALLS=yes VALGRIND=no DEBUG=yes
    - compiler: gcc
      env: CONFIGURE_OPTION='-Duse64bitall -Dusethreads -Dcc=gcc' COVERALLS=yes VALGRIND=no DEBUG=yes
    - compiler: clang
      env: CONFIGURE_OPTION='-Dcc=clang' COVERALLS=yes VALGRIND=no DEBUG=yes TEST_JOBS=3

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential libtool
  - sudo apt-get build-dep perl perl-base

before_script:
  - ./Configure -des -Dusedevel -Uversiononly $CONFIGURE_OPTION -Dprefix=$HOME/perl-blead
script:
  - make test && make install && $HOME/perl-blead/bin/perlivp
after_script:
cache:
  apt: true

